import express from "express";
import { createServer } from "http";
import { Server } from "socket.io";
import { createServer as createViteServer } from "vite";
import path from "path";
import cors from "cors";
import { fileURLToPath } from "url";
import { GoogleGenAI } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function startServer() {
  const app = express();
  const httpServer = createServer(app);
  const io = new Server(httpServer, {
    cors: {
      origin: "*",
      methods: ["GET", "POST"]
    }
  });

  const PORT = 3000;

  app.use(cors());
  app.use(express.json());

  // API routes
  app.get("/api/health", (req, res) => {
    res.json({ status: "Edge Sentinel Online", timestamp: new Date().toISOString() });
  });

  app.post("/api/analyze", async (req, res) => {
    try {
      const { prompt } = req.body;
      if (!prompt) return res.status(400).json({ error: "Prompt is required" });

      // Priority: 1. API_KEY (from key selector), 2. GEMINI_API_KEY (free key)
      let apiKey = process.env.API_KEY || process.env.GEMINI_API_KEY;
      
      // Sanitize: remove quotes, trim, and check for placeholder strings
      if (apiKey) {
        apiKey = apiKey.replace(/['"]/g, '').trim();
        if (apiKey === "undefined" || apiKey === "null" || apiKey === "MY_GEMINI_API_KEY" || apiKey === "") {
          apiKey = undefined;
        }
      }

      if (!apiKey) {
        return res.status(503).json({ error: "AI Engine not configured. Please authorize API access in the Security panel or set GEMINI_API_KEY in secrets." });
      }

      const ai = new GoogleGenAI({ apiKey });
      const response = await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: `As Edge Sentinel AI, analyze this security telemetry or query: "${prompt}". Provide a concise, technical security assessment optimized for Snapdragon 480 5G edge constraints.`,
        config: {
          systemInstruction: "You are Edge Sentinel AI, a local-first security intelligence suite. Your tone is technical, precise, and authoritative. You specialize in Android/Termux security telemetry analysis.",
        }
      });
      
      const text = response.text || "No analysis generated by the AI model.";
      res.json({ text });
    } catch (error: any) {
      console.error('AI Analysis failed:', error);
      
      // Check for specific API key errors
      const errorMessage = error?.message || "";
      if (errorMessage.includes("API key not valid") || errorMessage.includes("400") || errorMessage.includes("401")) {
        return res.status(401).json({ error: "Invalid API Key. Please re-authorize or check your secrets." });
      }
      
      res.status(500).json({ error: "Sentinel AI offline", details: errorMessage });
    }
  });

  // Global error handler
  app.use((err: any, req: express.Request, res: express.Response, next: express.NextFunction) => {
    console.error('Unhandled server error:', err);
    res.status(500).json({ error: "Internal Server Error", message: err.message });
  });

  // Telemetry Simulation
  const telemetryData = {
    cpu_usage: 0,
    memory_usage: 0,
    network_traffic: 0,
    threat_level: "Low",
    active_connections: [],
    logs: []
  };

  const generateLog = () => {
    const events = [
      "Inbound connection from 192.168.1.45",
      "Sentinel AI scanning process: 4567",
      "Memory spike detected in Termux environment",
      "Encrypted packet received on port 8001",
      "Snapdragon 480 NEON optimization active",
      "Threat analysis: No anomalies found",
      "Local-first buffer flush complete"
    ];
    return {
      timestamp: new Date().toLocaleTimeString(),
      message: events[Math.floor(Math.random() * events.length)],
      type: Math.random() > 0.8 ? "warning" : "info"
    };
  };

  setInterval(() => {
    telemetryData.cpu_usage = Math.floor(Math.random() * 40) + 10;
    telemetryData.memory_usage = Math.floor(Math.random() * 30) + 20;
    telemetryData.network_traffic = Math.floor(Math.random() * 500) + 50;
    
    if (Math.random() > 0.95) {
      telemetryData.threat_level = "Medium";
      telemetryData.logs.unshift({
        timestamp: new Date().toLocaleTimeString(),
        message: "Anomalous network pattern detected",
        type: "danger"
      });
    } else {
      telemetryData.threat_level = "Low";
    }

    if (telemetryData.logs.length > 50) telemetryData.logs.pop();
    if (Math.random() > 0.7) {
      telemetryData.logs.unshift(generateLog());
    }

    io.emit("telemetry_update", telemetryData);
  }, 2000);

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  httpServer.listen(PORT, "0.0.0.0", () => {
    console.log(`Edge Sentinel Dashboard running on http://localhost:${PORT}`);
  });
}

startServer();
